site_name: McGill CS Study Recruitment
site_url: https://www.cs.mcgill.ca/~mschie3/recruitment
nav:
    - Study Information: study-and-recruitment.md
    - Legal Information: administrative-and-legal.md
theme:
  name: material
  logo: assets/logo.png
  palette:
    scheme: mcgill
    accent: red
extra_css:
    - stylesheets/extra.css
markdown_extensions:
    - tables
    - pymdownx.tabbed:
        alternate_style: true 
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

